#
# Changes to this file will be overwritten by `trmnlp pull`.
#
# Docs: https://help.usetrmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
#
---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: 'https://frank-energie-api.netlify.app/api'
polling_headers: ''
icon: media/icon.svg
name: Frank Energie
refresh_interval: 1440
custom_fields:
- keyname: resource_type
  field_type: select
  name: Resource to Display
  description: Choose which resource data to show in charts and main stats
  options:
  - "Electricity"
  - "Gas"
  default: "Electricity"
- keyname: author_bio
  field_type: author_bio
  name: Author Bio
  description: Short support bio shown to end users
  category: "environment,finance"
  default: "Ivan Perez (taichikuji)"
